# export PIP_INDEX_URL="https://pkg.geely.com/artifactory/api/pypi/pypi/simple"
# export PIP_EXTRA_INDEX_URL="https://pkg.geely.com/artifactory/api/pypi/nvidia-pypi-remote-hz/simple"

# pip install transformers==4.46.1
# pip install accelerate==0.34.0

if [ -n "$MLP_WORKER_NUM" ]; then
  NNODES="$MLP_WORKER_NUM"
  GPUS_PER_NODE=8
else
  NNODES=1
  GPUS_PER_NODE=1
fi

cd /path/to/MeGan/

OUT_MODEL_DIR="/path/to/MeGan/checkpoint/"

PROJECT_NAME="metaSwiGLU-test"
BASE_MODEL_NAME="Llama-3.2-1B-Instruct"
STAGE="sft"
DATA="Shakespeare_qa"
STYLE_PROMPT_TYPE="inSystem"
STYLE_EXPRESSION_TYPE="withInstruction"
META_ATTN_KEY="x"
META_ATTN_HEAD_NUM=4
META_MLP_BIAS=1
META_NUM_LAYER=1
LAMBDA=0
MICRO_BATCH_SIZE=2
GRAD_ACC=1
LEARN_RATE=1e-4
DECAY=1e-2
TRAIN_EPOCH=1
BSZ=$((NNODES*GPUS_PER_NODE*MICRO_BATCH_SIZE*GRAD_ACC))
OUTPUT_MODEL_NAME=$PROJECT_NAME"-attn_k_"$META_ATTN_KEY"_h"$META_ATTN_HEAD_NUM"_b"$META_MLP_BIAS"_l"$META_NUM_LAYER"-"$STAGE"-"$BASE_MODEL_NAME"-"$DATA"-Lambda"$LAMBDA"-LR"$LEARN_RATE"-decay"$DECAY"-bsz"$BSZ"-epoch"$TRAIN_EPOCH

MODEL_NAME=$BASE_MODEL_NAME \
TOKENIZER_NAME=$BASE_MODEL_NAME \
OUTPUT_PATH=$OUT_MODEL_DIR$OUTPUT_MODEL_NAME \
TEMPLATE="llama3" \
STYLE_PROMPT=$STYLE_PROMPT_TYPE \
STYLE_EXPRESSION=$STYLE_EXPRESSION_TYPE \
FINETUNE_TYPE="meta_swiglu" \
TRAIN_STAGE=$STAGE \
DATASET=$DATA \
LR=$LEARN_RATE \
WEIGHT_DECAY=$DECAY \
PER_DEVICE_BATCH_SIZE=$MICRO_BATCH_SIZE \
GRADIENT_ACCUMULATION_STEPS=$GRAD_ACC \
EPOCH=$TRAIN_EPOCH \
META_SWISHGLU_ATTEN_KEY=$META_ATTN_KEY \
META_SWISHGLU_ATTEN_HEAD_NUM=$META_ATTN_HEAD_NUM \
META_SWISHGLU_MLP_BIAS=$META_MLP_BIAS \
META_SWISHGLU_BETA_N_LAYER=$META_NUM_LAYER \
Meta_L2_LAMBDA=$LAMBDA \
PREPROCESS_WORKERS=1 \
sh train_meta_swish/run_meta_swiglu_sft_template.sh

rm -rf $OUT_MODEL_DIR$OUTPUT_MODEL_NAME/checkpoint-*
